---
- hosts: all
  gather_facts: no
  become: True
  tasks:
    - name: Update a users password
      user:
        name: ats
        update_password: always
        password: $6$rounds=656000$sLMm7JgcxnV8c0hB$uY1OZWfIOvw4I2inwSZHHUY1gu02R.iWwhc39AB8urZXyAnv3Fh.T4Ep//eglm8HZWTwXtpzjY5OV/
